theme: jekyll-theme-cayman
title: Anxo López Rodríguez
description: Anxo López Rodríguez

# Configuración de layouts por defecto
defaults:
  - scope:
      path: "assets/apuntes"
    values:
      layout: "apuntes"
      author: "Anxo López Rodríguez"
